<?php 
/*
*****AUTOGENERATED FILE*****
 CREATED ON:Sun Aug 3 2014 1:08:54
*/
$schema['usr_id'] = array('attributes'=> array('type'=>'int', 'is_null'=>'NO', 'max_length'=>'', 'column_key' =>'PRI'));
$schema['usr_fname'] = array('attributes'=> array('type'=>'varchar', 'is_null'=>'NO', 'max_length'=>'120', 'column_key' =>''));
$schema['usr_lname'] = array('attributes'=> array('type'=>'varchar', 'is_null'=>'NO', 'max_length'=>'120', 'column_key' =>''));
$schema['usr_username'] = array('attributes'=> array('type'=>'varchar', 'is_null'=>'NO', 'max_length'=>'50', 'column_key' =>''));
$schema['usr_password'] = array('attributes'=> array('type'=>'varchar', 'is_null'=>'NO', 'max_length'=>'40', 'column_key' =>''));
$schema['usr_email'] = array('attributes'=> array('type'=>'varchar', 'is_null'=>'NO', 'max_length'=>'50', 'column_key' =>''));
$schema['pri'] = 'usr_id';
$schema['db_name'] = 'tutelage_db'; 
?> 